spring.application.name=Backend_secureRealty
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=SecureRealtyDB

chat.server.url=http://localhost:8080
jwt.secret=ThisIsMySuperSecretKeyForSecureRealtyApplication123456789